const mongoose = require("mongoose");

const CouponSchema = new mongoose.Schema(
  {
    // id autogenerated.
    name: { type: String, require: true }, // required internal use.
    description: { type: String, default: "", maxlength: 5000 }, // optinal internal use
    code: { type: String, require: true, unique: true },
    isPercent: { type: Boolean, require: true, default: true },
    amount: { type: Number, required: true }, // if is percent, then number must be ≤ 100, else it’s amount of discount
    expireDate: { type: Date, require: true, default: new Date() },
    isActive: { type: Boolean, require: true, default: true },

    // maybe add category exception or product exception funcionalites later.
  },
  {
    timestamps: true,
  }
);

const Coupon = new mongoose.model("Coupon", CouponSchema);

module.exports.Coupon = Coupon;
